export const projects = [
  {
    id: 1,
    title: "Algo-arena (Leetcode Clone)",
    description:
      "A Leetcode clone with a focus on algorithm challenges and community solutions.",
    image: "/algo-arena.png",
    category: "fullstack",
    tags: [
      "Next.js",
      "Bun",
      "Postgres",
      "Judge0",
      "Vercel",
      "Tailwind CSS",
      "Redis",
      "TurboRepo",
    ],
    liveUrl: "https://algo-arena-web.vercel.app/",
    githubUrl: "https://github.com/Arjun149133/algo-arena",
    live: true,
  },
  {
    id: 2,
    title: "MultiPlayer Chess",
    description:
      "Real-time multiplayer chess game with user authentication and matchmaking.",
    image: "/chess-game.png",
    category: "fullstack",
    tags: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "WebSocket",
      "Docker",
      "TurboRepo",
      "CI/CD",
      "Express",
      "postgreSQL",
    ],
    liveUrl: "https://chess-application-web.vercel.app/",
    githubUrl: "https://github.com/Arjun149133/chess-application",
    live: false,
  },
  {
    id: 3,
    title: "CollabDraw (Excalidraw Clone)",
    description:
      "Collaborative drawing app with real-time features and user authentication. Where users can create and share drawings.",
    image: "/collabdraw.png",
    category: "fullstack",
    tags: [
      "Next.js",
      "Canvas",
      "Shadcn",
      "WebSocket",
      "Docker",
      "TurboRepo",
      "CI/CD",
      "Express",
      "postgreSQL",
    ],
    liveUrl: "https://collabdraw.arjunyadav.website",
    githubUrl: "https://github.com/Arjun149133/excalidraw-clone",
    live: false,
  },
  {
    id: 4,
    title: "Twitter Clone",
    description:
      "A Twitter clone with user authentication, real-time updates, and a responsive design.",
    image: "/twitter-clone.png",
    category: "fullstack",
    tags: ["Next.js", "Taiwind CSS", "Firebase", "FireStore", "Recoil"],
    liveUrl: "https://twitter-clone-psi-henna.vercel.app/",
    githubUrl: "https://github.com/Arjun149133/twitter-clone",
    live: true,
  },
  {
    id: 5,
    title: "Job Portal",
    description:
      "A full-stack job portal where users can post job listings and apply for jobs, featuring user authentication and role-based access.",
    image: "/job-portal.png",
    category: "fullstack",
    tags: [
      "Next.js",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Tailwind CSS",
      "JWT",
      "Vercel",
      "REST API",
    ],
    liveUrl: "https://job-board-mini-assignment-frontend.vercel.app/",
    githubUrl: "https://github.com/Arjun149133/job-board-mini-assignment",
    live: true,
  },
  {
    id: 6,
    title: "Finance Tracker",
    description:
      "A full-stack finance tracker that allows users to manage income and expenses with an intuitive UI and seamless API integrations.",
    image: "/finance-tracker.png",
    category: "fullstack",
    tags: [
      "Next.js",
      "MongoDB",
      "Node.js",
      "Express",
      "Tailwind CSS",
      "REST API",
      "Vercel",
    ],
    liveUrl: "https://finance-tracker-assignment-phi.vercel.app/",
    githubUrl: "https://github.com/Arjun149133/Finance-Tracker-Assignment",
    live: true,
  },
  {
    id: 7,
    title: "Flappy Bird",
    description:
      "A fun and lightweight Flappy Bird clone built with React and Tailwind CSS. A simple project created just for fun and practice.",
    image: "/flappy-bird.png",
    category: "frontend",
    tags: ["React", "Tailwind CSS", "JavaScript", "Vercel"],
    liveUrl: "https://flappy-bird-orcin-seven.vercel.app/",
    githubUrl: "https://github.com/Arjun149133/flappy-bird",
    live: true,
  },
  {
    id: 8,
    title: "E-commerce Landing Page",
    description:
      "A pixel-perfect, fully responsive e-commerce landing page with smooth carousel animations. Built using React and Tailwind CSS.",
    image: "/loyalty-ecommerce.png",
    category: "frontend",
    tags: [
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Responsive Design",
      "Carousel",
      "Vercel",
    ],
    liveUrl: "https://loyalty-ecommerce.vercel.app/",
    githubUrl: "https://github.com/Arjun149133/loyalty-ecommerce",
    live: true,
  },
];
